export const USER_ACTIONS = {
  SET_CURRENT_USER: 'user/SET_CURRENT_USER',
  CHECK_USER_SESSION: 'user/CHECK_USER_SESSION',
  EMAIL_SIGN_IN: 'user/EMAIL_SIGN_IN',
  GOOGLE_SIGN_IN: 'user/GOOGLE_SIGN_IN',
  SIGN_IN_SUCCESS: 'user/SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'user/SIGN_IN_FAILURE',
};
